import { useEffect, useState } from "react"
import Head from 'next/head'

export default function Home() {
const [catalogueData, setCatalogueData] = useState()
  const [defaultAlbumData, setDefaultAlbumData] = useState()
  const [selectedAlbumData, setSelectedAlbumData] = useState()
useEffect(() => {
      fetchData()
    }, [])

  const fetchData = async () => {
    try {
      const response = await fetch(
      "https://matthewviamusic.com/api/tracks"
    )
      const catalogueData = await response.json()

      setCatalogueData(catalogueData) 
      setDefaultAlbumData(catalogueData?.filter((x) => x.albumName == "A Government in Heaven")) 
      
  } catch (error) {
      console.log('ERROR>>>>>:', error)
  } 
  
  if (!catalogueData) return {notFound: true} // 404 page
  
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {JSON.stringify(catalogueData)}
      </main>
    </>
  )
}
